"""Pydantic v2 Contracts for System Two Generative Engine."""

from typing import Any
from pydantic import BaseModel, Field

class DecisionTelemetry(BaseModel):
    """Calibrated System One decision telemetry returned with every chat turn."""

    intent: str
    intent_confidence: float
    sentiment_score: float
    sentiment_level: str
    sentiment_confidence: float
    needs_escalation: bool
    escalation_confidence: float
    system_one_latency_ms: float


class SystemTwoRequest(BaseModel):
    """Input payload for System Two deliberation and text/code generation."""

    message: str = Field(..., min_length=1, description="User prompt or instruction.")
    history: list[dict[str, str]] = Field(
        default_factory=list, description="Prior conversational turns."
    )
    temperature: float | None = Field(
        default=None, ge=0.0, le=2.0, description="Sampling temperature override."
    )
    max_tokens: int | None = Field(
        default=None, ge=1, le=8192, description="Maximum tokens to generate."
    )
    stream: bool = Field(
        default=False, description="Whether to stream tokens via generator."
    )


class SystemTwoResponse(BaseModel):
    """Output payload from System Two containing generated text/code and System 1 telemetry."""

    reply: str = Field(..., description="Generated text, code, or explanation.")
    telemetry: DecisionTelemetry = Field(
        ..., description="Calibrated System One decision telemetry that guided generation."
    )
    model_name: str = Field(
        default="qwen2.5-coder:latest", description="Name of underlying generative model."
    )
    total_latency_ms: float = Field(
        ..., description="Total wall-clock latency including System 1 and System 2."
    )
    token_count: int | None = Field(
        default=None, description="Number of tokens generated by System 2."
    )


class StreamChunk(BaseModel):
    """Incremental event chunk for real-time token streaming."""

    delta: str = Field(..., description="Incremental token text.")
    done: bool = Field(default=False, description="Whether generation is complete.")
    telemetry: DecisionTelemetry | None = Field(
        default=None, description="System 1 telemetry emitted on first chunk."
    )
